server:
  port: 8080

spring:
  application:
    name: rica-api

  datasource:
    url: jdbc:postgresql://localhost:5432/rica
    username: rica
    password: rica

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        hibernate.default_schema: public
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  mongodb:
    uri: mongodb://localhost:27017/rica